### ISSUE TITLE
setup.py not works

### ISSUE THREAD

**Issue by Ryo-PurpleEye** [NNgen/nngen#1]
By including non-ASCII characters In README.rst, setup.py not works:
| cont@ubuntu18# python3 setup.py install
| Traceback (most recent call last):
|   File "setup.py", line 18, in <module>
|     long_description=read('README.rst'),
|   File "setup.py", line 8, in read
|     return open(os.path.join(os.path.dirname(__file__), filename)).read()
|   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
|     return codecs.ascii_decode(input, self.errors)[0]
| UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5888: ordinal not in range(128)

It might work In JP locale, but not tried.
With replacing 2-byte chars to ascii chars (', ", etc.), setup.py ran correctly.

You can check these non-ascii chars:
    sed -e 's/[!-~\t \r\n\?]//g' README.rst  | grep -nv '^$'

**Comment by shtaxxx** [comment]
Thank you for the very important information!

README.rst is generated from README.md via Pandoc. In the conversion process of Pandoc, some characters unfortunately are replaced with 2-byte characters.

I will update the conversion process, or will update README.rst manually.

**Comment by shtaxxx** [comment]
This issue has been resolved in 7e5a4480f08b4bb20fc6d126dd626361efc74bc7 . Thanks!
