### ISSUE TITLE
Version constraints on the required ONNX modules are too strong.

### ISSUE THREAD

**Issue by RyusukeYamano** [NNgen/nngen#45]
The ONNX module version constraint is too strong, so pip installation may not be able to resolve dependencies with other modules.
The problem is especially likely to occur when adding learning modules such as pytorch.

**Comment by shtaxxx** [comment]
I agree. Now I'm using `onnx==1.9.0` in my test environment.

**Comment by RyusukeYamano** [comment]
Sounds like great!

**Comment by shtaxxx** [comment]
The dependent version is changed in 7ef5b4892a922c8945231d6a655711d5a30a8326 .
